### ISSUE TITLE
Parsing of timedata is buggy (?)

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/fmu-dataio#101]
https://github.com/equinor/fmu-dataio/blob/b35a3176af2c809083536c5d629b91424e14bbf3/src/fmu/dataio/_export_item.py#L409
Working on a string from the timedata list, but then taking the first element, which becomes the first character. Leads to this in the wild:
```
ValueError: time data '2' does not match format '%Y%m%d'
```
Input to dataio is e.g.:
```
timedata=["20150101", "20210101"]
```

**Comment by perolavsvendsen** [comment]
Actually, probably works as expected - it expects input as list of lists. Suggest to include a check for this and throw error if input is not list of lists. Alternatively, allow for list of dates in addition to list of lists.

**Comment by jsorb** [comment]
Actually, it seems like this may be intentional, but it makes no sense. These filenames do not work on windows and they are ugly as hell. At least, the sequence of them should not be switched. When 20210515 is input as the first list, it should show up first in the file name.

**Comment by jcrivenaes** [comment]
It was not intentional that filenames had clock times (although it _can be discussed_; what if timedata for e.g. a well test comes within the same date?). File names with ":" are not windows compatible so of course that shall change. 

The order of the dates was also something we discussed and we need to land on that: Given [[20100101, "first"], [20200101, "second"], then technically the diff map or property is "second-first"?

A last comment is that file names are purely informal. The file names themselves are not parsed in SUMO; it is the metadata file only.

**Comment by jcrivenaes** [comment]
From seismic best practice: monitor-base: `[[20210101, "monitor"], [19990101, "base"]] `giving filenames `some--20200101_19990101`. A rewording in the docs is also needed

**Comment by jcrivenaes** [comment]
Think this can be closed now? @perolavsvendsen @berland ?
