### ISSUE TITLE
Expand content whitelist

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-dataio#331]
When exporting tabular data from flow simulators like eclipse or opm the current whitelist ALLOWED_CONTENT is too narrow.
list is currently (commit 949e906) the highest level:
depth, time, thickness, property, seismic, fluid_contact, fluid_outline, field_region, regions, pinchout, subcrop, fault_lines, velocity, volumes, volumetric, khproduct, and timeseries. See [_definitions](https://github.com/equinor/fmu-dataio/blob/main/src/fmu/dataio/_definitions.py)

Of these it is only khproduct, volumetrics, and timeseries that are relevant to simulator results.

**Comment by perolavsvendsen** [comment]
Yes, the list is not exhausted by any means. We have usually expanded it when explicit needs are uncovered, through separate issues.

Suggest to make specific issues for specific allowed contents so that they better can be done and closed. 

Ideally, allowed contents should correspond to defined (data) products produced by FMU workflows. It is, however, also influenced by legacy contracts with e.g REP and others.

**Comment by perolavsvendsen** [comment]
Closing this, we expand the whitelisted contents regularly on an as-needed basis. The `content` is a crucial metadata tag, as it is basically the only one that says what a piece of data actually _is_. Ref discussions on data products.
