### ISSUE TITLE
Support for faultdata on JSON format, related to DynaGeo

### ISSUE THREAD

**Issue by jcrivenaes** [equinor/fmu-dataio#362]
This issue details and discuss/matures implementation of fault data initially made by DynaGeo internal link: https://dynageo.app.radix.equinor.com/). However the fault format itself is not strictly tied to DynaGeo. As this is JSON (~dictionary) format, the issue is related to #361 .

Fault format example
```
{
  "type": "FeatureCollection",
  "crs": {
    "type": "name",
    "properties": {
      "name": "EPSG::23032"
    }
  },
  "features": [
    {
      "type": "Feature",
      "properties": {
        "FaultID": "CF_C2",
        "HorizonID": "TopTilje322",
        "SegmentID": 0,
        "TriangleID": 0,
        "Juxtaposition": 0.0,
        "permeability_max": 0.54999997317791,
        .....
        "shalegougeratio_avg": 0.20000000298023224
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              422238.404,
              7247491.896,
              2277.951
            ],
            [
              422241.016,
              7247492.562,
              2275.44
            ],
            [
              422231.777,
              7247516.006,
              2275.822
            ],
            [
              422238.404,
              7247491.896,
              2277.951
            ]
          ].
...
```
Each triangle (note that first and last coordinate are identical) have several properties. The files can become quite big.

**Comment by jcrivenaes** [comment]
The metadata shall contain at least related to to the data object:
```
Juxtaposition:
FW_Tilje321_Tilje322_Tilje323_HW_Tilje321_Tilje322_Tilje323

Parameters exported:
Juxtaposition
displacement_min
multiplier_avg
multiplier_min
permeability_avg
permeability_max
shalegougeratio_avg
shalegougeratio_min
shalesmearfactor_avg
shalesmearfactor_max
thickness_min
transmissibility_avg
transmissibility_min

Horizons:
TopTilje322

```

**Comment by perolavsvendsen** [comment]
For other datatypes that have a content-specific subtag under `data`, e.g. `field_outline`, `fluid_contact` and others, we have strictly used the same phrasing. So in the proposal above, suggest using `data.faultplane` (instead of `data.faultdata`).

**Comment by jcrivenaes** [comment]
> Also, this looks like `GeoJSON`? Would it make more sense to be explicit with `class: geojson`? (Or would that be handled by `data.format: geojson`?)

Certainly; need to consider. Having only JSON is too general probably

**Comment by perolavsvendsen** [comment]
Notes based on offline discussions with the data producer 08.09.2023:

Sounds something like this:
```
class: polygons
data.content: faultroom # <-- too specific? Worried about other, future faultseal products...
data.format: geojson
```

...and then a content-specific tag that carries the needed information from the source, e.g.
```
data.faultroom:
   parameters: [list of parameters],
   juxtaposition:
      fw: [list of faults]
      hw: [list of faults]
   etc: etc
   etc: etc # can be expanded as needed
```

According to the data producer, each geojson file contains multiple triangles repeating downwards, where each contains e.g. the list of parameters - but this is consistent through the file.

They currently export "metadata" next to the data files, which is an extract of some of these things. However, it is on plain text format not very suited for machine reading. They also communicate list of zones as an underscore-separated string, which will not work - zone names can (and frequently does) contain underscore. Suggested to get this in a more explicit format, for instance `json`.

**Comment by perolavsvendsen** [comment]
Status 18. Dec 2023
- Functionality now in place in `FaultRoom` for exporting data with (embedded) metadata

Next steps probably:
- [ ] Include necessary definitions in FMU data standard (schema), i.e. `content` and others.
- [ ] `fmu-dataio` knows the FaultRoom export, extract necessary metadata from datafile, insert into FMU metadata.
- [ ] `fmu-dataio` able to export FaultRoom-generated data during FMU runs, with valid FMU metadata attached.
- [ ] Agree on which metadata elements from the FaultRoom format that needs to be lifted out into FMU metadata, in order to find correct data, etc.

**Comment by perolavsvendsen** [comment]
Discussions 15. Jan 2024
- Faultroom exports to a chosen export folder
- [ ] Script is needed to run fmu-dataio to "re-"export these data. Consider putting them in a temporary location from FaultRoom, e.g. `share/results/tmp/faultroom`
- [ ] Decide on `content` (suggest "fault_properties") and `class` (suggest "triangulated_polygons") and `format` (suggest "GeoJSON")

Next steps:
- [ ] Need concrete example of a project where these data are exported (i.e. FaultRoom is included and exporting data). Prefer this do be done in Drogon. (Note that DynaGeo depends on correct CRS, so data produced by Drogon will not be plottable in DynaGeo. However, several steps can be taken with Drogon without the need for _visualizing_ the data.)
[as list from previous discussions]

FaultRoom use case differ from other RMS-related use cases where the data is normally parsed directly from RMS, then exported. In this case, data is exported out of RMS by another process, and then fmu-dataio needs to read them back from disk in order to export them.

Current version of FaultRoom used by DynaGeo: `1.3.1rc5`
