### ISSUE TITLE
Transition to Pydantic Models for Data Construction

### ISSUE THREAD

**Issue by janbjorge** [equinor/fmu-dataio#457]
We're currently facing challenges with our data management due to the use of plain Python dictionaries for constructing and manipulating data. This approach has leads to difficulties in understanding and predicting the structure of our data, as there's no explicit definition of the schema we're working with. To address this issue, I propose the transition to use Pydantic models for data construction.

### Current Situation
- Data is dynamically constructed and manipulated using Python dictionaries.
- Lack of explicit schema definitions makes it hard to understand the structure and content of the data without resorting to `print` statements for debugging.
- This approach increases the risk of runtime errors and bugs due to unexpected data structures or missing/extra fields.

### Proposed Solution
- Use Pydantic models to defined schemas for our data structures.
- This will provide several benefits:
  - **Type checking**: Ensures that our data conforms to the defined schema at runtime, catching errors early.
  - **Editor support**: Improves autocompletion, linting, and type hints in IDEs.
  - **Documentation**: Pydantic models can be easily documented, improving code readability and maintainability.
  - **Serialization/Deserialization**: Simplifies conversion between dictionaries and model instances, making it easier to work with data in APIs, databases, etc.

**Comment by perolavsvendsen** [comment]
Regarding type checking - it is a requirement that fmu-dataio works also when being ran e.g. inside RMS, outside the FMU context. Example: A model user will frequently run RMS interactively. In this context, fmu-dataio will not produce _valid_ metadata (because the whole FMU context is missing). But it must still work.

Also, running RMS interactively, is one of the few places where errors are actually immediately visible to the user. It is important that fmu-dataio fail appropriately when running RMS interactively, so that the user can take corrective action (e.g. this is where you discover if you have a typo in the script, etc).

So, we can validate _parts of_ the data model, but not all of it.

The current code is context-aware. It knows when running inside RMS, and it knows when running outside the FMU context (i.e. not orchestrated by ERT).

**Comment by mferrera** [comment]
Based on offline discussions we are considering this task complete.
