### ISSUE TITLE
Removal of kwargs in export(...) and generate_metadata(...) functions

### ISSUE THREAD

**Issue by janbjorge** [equinor/fmu-dataio#525]
The current implementation of `export(...)` and `generate_metadata(...)` functions in our codebase allows for arbitrary keyword arguments (**kwargs). This approach has introduced unnecessary complexity and potential issues with code maintainability and readability. To improve our code's quality and ensure consistency, I propose we remove the **kwargs parameter from these functions.

This issue is opened for discussion, and I welcome any thoughts or concerns regarding this proposed change.

**Comment by perolavsvendsen** [comment]
This has been discussed multiple times lately, and I think there is convergence on that we need to stop allowing this (?).

Discussed in weekly meeting 10/4-2024

This is a blocker/complicating factor for e.g. #540. This may be depending on #595.

A consequence of allowing arguments in e.g. `.export()` combined with the pattern where arguments change the state (of `dataio.config`) is that we get unwanted confusion such as:

```python
# given "myvariable" in config, defaulted to True
exp = ExportData() # myvariable is defaulted to True
for x in xx:
  exp.export() # myvariable is defaulted to True
  exp.export(myvariable=False) # myvariable is False
  exp.export() # myvariable is False (!)
```

**Comment by perolavsvendsen** [comment]
Discussion 12/4-2024

For `.export()` and `.generate_metadata()`:
- Which keyword arguments do we want to still accept?
- For a while, continue accepting `**kwargs` but deprecate whatever comes through `**kwargs`


What can/will break?
- There are patterns today where most of the arguments are put into `.export()` rather than `ExportData.__init__()`. This will/may stop working.

- [ ] Agree on, and describe, the wanted pattern
- [ ] Add necessary new arguments, and the handling of these (do not change state!)
  - [ ] `name`
  - [ ] `tagname`
  - [ ] `classification`
  - [ ] etc
  - [ ] etc
- [ ] Update Drogon to the wanted pattern
- [ ] Notify user about wanted pattern
- [ ] Deprecate explicit arguments from `**kwargs`
- [ ] Eventually, consider fully discontinuing `**kwargs`
